name: Poetry publish
description: Publish
inputs:
  token:
    description: Pypi API Token
    required: true
  test:
    description: Publish to Pypi Test

runs:
  using: composite
  steps:
    - shell: bash
      run: poetry config repositories.pypi https://upload.pypi.org/legacy/
    - name: Use Test PyPi Repo
      if: inputs.test != ''
      shell: bash
      run: |
        poetry config repositories.pypi https://test.pypi.org/legacy/
    - name: Publish
      shell: bash
      run: |
        poetry config pypi-token.pypi ${{ inputs.token }}
        poetry publish -r pypi
