name: Docker Setup
description: Common docker setup steps
inputs:
  ecr_account:
    description: ECR AWS Account Number
  ecr_region:
    description: ECR Region
  ghcr_registry:
    description: Docker Registry
    default: ghcr.io
  ghcr_token:
    description: GitHub Container Registry Token
    required: true
outputs:
  ecr_registry:
    description: ECR Registry Hostname
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Configure AWS credentials
      if: ${{ inputs.ecr_account }}
      uses: aws-actions/configure-aws-credentials@acca2b1b2070338fb9fd1ca27ecee81d687e58e5 # v6.1.2
      with:
        aws-region: ${{ inputs.ecr_region }}
        role-to-assume: arn:aws:iam::${{ inputs.ecr_account }}:role/GitHubActionsECR
        role-session-name: ${{ github.event.repository.name }}-${{ github.run_number }}@${{ github.run_attempt }}

    - name: Login to Amazon ECR Private
      if: ${{ inputs.ecr_account }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5

    - name: Log in to GHCR
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}
