name: Docker Setup
description: Common docker setup steps
inputs:
  ecr_account:
    description: ECR AWS Account Number
  ecr_region:
    description: ECR Region
  ghcr_registry:
    description: Docker Registry
    default: ghcr.io
  ghcr_token:
    description: GitHub Container Registry Token
    required: true
outputs:
  ecr_registry:
    description: ECR Registry Hostname
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Configure AWS credentials
      if: ${{ inputs.ecr_account }}
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
      with:
        aws-region: ${{ inputs.ecr_region }}
        role-to-assume: arn:aws:iam::${{ inputs.ecr_account }}:role/GitHubActionsECR
        role-session-name: ${{ github.event.repository.name }}-${{ github.run_number }}@${{ github.run_attempt }}

    - name: Login to Amazon ECR Private
      if: ${{ inputs.ecr_account }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78 # v2.1.2

    - name: Log in to GHCR
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}
