title: "[Example - Add an easter egg in the Authentication Methods page!]"
labels: new
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to submit a new feature request to make Descope better!
  - type: markdown
    attributes:
      value: >
        Please first make sure that the feature you are requesting wasn't already submitted by a felow Descoper.

        You can do so by searching over all Descope Ideas in the portal.
        
        Is it already submitted? **Make sure to upvote it!** That's how we know what's most important for as many Descopers as possible 🙏🏼
  - type: markdown
    attributes:
      value: >
        When writing your idea, try to cover the following:

        * What is the problem you are trying to solve?
        
        * What solution did you envision for that problem?
        
        
        You can give a very detailed explanation, or make it simple, up to you.
        
        **The more information** - along with supporting elements such as images - **the better we will all understand and help!** 🪄
  - type: textarea
    id: Description
    attributes:
      label: Description
      placeholder: If the Descoper finds the hidden method - present them with a gif!
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Labels
      description: >
        Label the idea according to the feature it relates to (e.g. SDK, flows & screens...).
        
        If you are having trouble deciding, you can always label the idea as `other`.
      options:
        - label: I have labelled my idea
          required: true        
        
        
        
        
