name: Poetry Setup
description: Basic python setup with Poetry
inputs:
  python-version:
    description: Python version to use. Reads from .python-version if unset.
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - name: Get changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          py_modified:  
            - added|modified: "./**/*.py"

    - name: Setup Python
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Install dependencies
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: |
        poetry install

    - name: Black
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: poetry run black --check ${{ steps.filter.outputs.py_modified_files }}

    - name: Run flake8
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: poetry run flake8 ${{ steps.filter.outputs.py_modified_files }}
