name: Poetry Setup
description: Basic python setup with Poetry
inputs:
  python-version:
    description: Python version to use. Reads from .python-version if unset.
runs:
  using: composite
  steps:
    - name: Get changed files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        list-files: shell
        filters: |
          py_modified:  
            - added|modified: "./**/*.py"

    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install and configure Poetry
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Black
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: poetry run black --check ${{ steps.filter.outputs.py_modified_files }}

    - name: flake8
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: poetry run flake8 ${{ steps.filter.outputs.py_modified_files }}

    - name: isort
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      shell: bash
      run: poetry run isort --check --diff --profile black ${{ steps.filter.outputs.py_modified_files }}
