name: Docker Setup
description: Common docker setup steps
inputs:
  ecr_account:
    description: ECR AWS Account Number
  ecr_region:
    description: ECR Region
    default: eu-central-1
  registry:
    description: Docker Registry
    default: ghcr.io
  ghcr_token:
    description: GitHub Container Registry Token
    required: true
  image-name:
    description: Docker Image Name
    default: ${{ github.repository }}
outputs:
  ecr_registry:
    description: ECR Registry Hostname
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      if: ${{ inputs.ecr_account }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.ecr_region }}
        role-to-assume: arn:aws:iam::${{ inputs.ecr_account }}:role/GitHubActionsECR
        role-session-name: ${{ github.event.repository.name }}-${{ github.run_number }}@${{ github.run_attempt }}

    - name: Login to Amazon ECR Private
      if: ${{ inputs.ecr_account }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}
